### ISSUE TITLE
ImageNet Embedding: can't read images

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#20]
When trying to use ImageNet Embedding, I get several errors. One is surely connected to reading url files, but even when we stored images locally, I can't use ImageNet.

Error on OSX:
`AttributeError: 'str' object has no attribute 'read'`
Error on Windows & Linux:
`hyper.http20.exceptions.StreamResetError: Stream forcefully closed`

**Comment by inejc** [comment]
I don't think these two are connected.

The `AttributeError: 'str' object has no attribute 'read'` should be the same as in https://github.com/biolab/orange3-imageanalytics/issues/10. I'm not sure about the second error. Could you please submit this to Sentry so I can try to replicate it?

**Comment by inejc** [comment]
Closing this since the issue for the first error is already opened and the second error is fixed.

**Comment by ajdapretnar** [comment]
I don't think this is quite it.
I get `AttributeError: 'str' object has no attribute 'read'` even when I store my files locally. This is the problem. I can't do anything now on Mac.

Also, for me #22 doesn't solve anything. I am getting loads of StreamResetErrors and my images don't get embedded at all. This is on Windows.

So in essence, I can't use ImageNet Embedding anywhere.

**Comment by ajdapretnar** [comment]
Local files now work. I assume the issue was server-side. Waiting for reading html file in #26.
